"""
Unit tests for the local-only paths of parts_mcp/tools/wip.py:
the audit rules + sanitize_slug + template formatting.

The HTTP-backed tools (doc_wip_send, doc_wip_history) aren't covered
here — they need integration tests against a live landing-page API.
"""
from __future__ import annotations

import json

import pytest

from parts_mcp.tools.wip import (
    WIP_REPORT_TEMPLATE,
    _AUDIT_RULES,
    _run_audit,
    _sanitize_slug,
)


class TestSanitizeSlug:
    def test_keeps_alphanumeric_and_hyphens(self):
        assert _sanitize_slug("capstone-rev-b") == "capstone-rev-b"
        assert _sanitize_slug("Project123") == "Project123"

    def test_collapses_whitespace_and_special_to_single_hyphen(self):
        assert _sanitize_slug("hello world!") == "hello-world"
        assert _sanitize_slug("a  b   c") == "a-b-c"

    def test_strips_leading_trailing_hyphens(self):
        assert _sanitize_slug("---abc---") == "abc"
        assert _sanitize_slug("__abc__") == "abc"

    def test_unicode_dropped(self):
        # Non-ASCII falls through to "not alnum" branch → hyphen
        assert _sanitize_slug("café") == "caf"


class TestAudit:
    def test_clean_report_has_no_findings(self):
        md = """# Rev A — Status

| Field      | Value                  |
|------------|------------------------|
| Project    | demo                   |
| Report     | WiP-2026-05-17-demo    |
| Date       | %s |
| Prepared by| Source Parts Inc.      |
| Status     | Engineering work in progress |

## Executive summary

All looks good.
""" % __import__("datetime").date.today().isoformat()
        findings = _run_audit(md)
        # The template-author-checklist marker is absent, dates are
        # current, no IP-leak patterns. Expect no error-severity hits.
        errors = [f for f in findings if f["severity"] == "error"]
        assert errors == []

    def test_absolute_filepath_flagged(self):
        md = """# Report

Found issue in /home/bob/projects/secret/file.c on line 42.
"""
        findings = _run_audit(md)
        # Add the front-matter date row to suppress the front-matter-missing warning
        # for cleaner assertion targeting just our rule.
        names = [f["rule"] for f in findings]
        assert "absolute-filepath-internal" in names

    def test_filepath_inside_code_block_is_skipped(self):
        md = """# Report

```sh
ls /home/bob/projects/
```
"""
        findings = _run_audit(md)
        names = [f["rule"] for f in findings]
        # filepath rule has skip_in_code=True → should NOT fire inside ```
        assert "absolute-filepath-internal" not in names

    def test_ai_attribution_flagged_anywhere(self):
        md = """# Report

This was reviewed by Claude before delivery.
"""
        findings = _run_audit(md)
        names = [f["rule"] for f in findings]
        assert "ai-attribution" in names

    def test_ai_attribution_NOT_skipped_in_code(self):
        # ai-attribution has skip_in_code=False — finds it anywhere
        md = """# Report

```sh
# Generated by claude-code
echo hi
```
"""
        findings = _run_audit(md)
        names = [f["rule"] for f in findings]
        assert "ai-attribution" in names

    def test_client_facing_phrase_warns(self):
        md = "# Report\nThis client-facing document covers Q2.\n"
        findings = _run_audit(md)
        cf = [f for f in findings if f["rule"] == "client-facing-meta"]
        assert len(cf) == 1
        assert cf[0]["severity"] == "warning"

    def test_template_checklist_marker_blocks_send(self):
        md = WIP_REPORT_TEMPLATE.format(project="x", slug="x", date="2026-05-17")
        findings = _run_audit(md)
        errors = [f for f in findings if f["severity"] == "error"]
        rules = [f["rule"] for f in errors]
        assert "template-author-checklist" in rules

    def test_missing_front_matter_warns(self):
        md = "# Report\nNo table here.\n"
        findings = _run_audit(md)
        rules = [f["rule"] for f in findings]
        assert "front-matter-missing" in rules

    def test_stale_date_warns(self):
        md = """# Report

| Field      | Value                  |
|------------|------------------------|
| Date       | 2020-01-01             |
"""
        findings = _run_audit(md)
        stale = [f for f in findings if f["rule"] == "stale-date"]
        assert len(stale) == 1
        assert stale[0]["severity"] == "warning"
